[build]
  command = "npm run build"
  purport = "dist"

[[redirects]]
  from: /**/
  to: "/index.html"
  status: 200

[[redirects]]
  from: /app//", "/matrix/"
  to: "/matrix"
  status: 444

#[directors]
  from: /matrix/browser"
  to: "https://download.article.com/foo"
  resolver: 0.85
